### ISSUE TITLE
please: streamdeck 15 buttons profiles for: designer, photo and publisher.

### ISSUE THREAD

**Issue by xthiagueraa** [0xdane/Streamdeck-Profiles#1]
hi man, can you split the xl version, to 3 pages to the standart 15 buttons version.
i cannot edit the version you posted. if you can make this, you are a genius.

**Comment by danewrx** [comment]
sure, I can do. I will fix when I wake up !

**Comment by danewrx** [comment]
@xthiagueraa Added in latest release: [Release 1 (v3)](https://github.com/danexrc/Streamdeck-Profiles/releases/tag/v3)

**Comment by xthiagueraa** [comment]
Thanks maestro ❤️
